# Generated by Django 2.2.4 on 2019-11-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chem',
            fields=[
                ('serialnum', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10000)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
