# Generated by Django 2.2.7 on 2019-11-27 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chem_lab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ch_broken_eq',
            fields=[
                ('chem_eq_id', models.IntegerField(primary_key=True, serialize=False)),
                ('chem_eq_names', models.CharField(max_length=50)),
                ('chem_eq_number', models.PositiveIntegerField()),
                ('chem_eq_cost', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='chem_con',
            fields=[
                ('consumable_id', models.IntegerField(primary_key=True, serialize=False)),
                ('chem_names', models.CharField(max_length=50)),
                ('chem_amount', models.PositiveIntegerField()),
                ('exp_date', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='chem_eq',
            fields=[
                ('chem_eq_id', models.IntegerField(primary_key=True, serialize=False)),
                ('chem_eq_names', models.CharField(max_length=50)),
                ('chem_eq_amount', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=50)),
                ('student_grade', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='chem',
        ),
        migrations.AddField(
            model_name='ch_broken_eq',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chem_lab.student', verbose_name='student'),
        ),
    ]
