# Generated by Django 2.2.7 on 2019-11-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chem_lab', '0003_auto_20191129_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ch_broken_eq',
            name='student',
            field=models.PositiveIntegerField(),
        ),
    ]
