# Generated by Django 2.2.7 on 2019-11-29 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chem_lab', '0004_auto_20191129_1639'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student',
        ),
    ]
