# Generated by Django 2.2.7 on 2019-11-30 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chem_lab', '0006_auto_20191130_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ch_broken_eq',
            name='chem_eq_number',
        ),
    ]
