# Generated by Django 2.2.8 on 2019-12-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_grade', models.PositiveIntegerField()),
                ('student_section', models.CharField(max_length=500)),
                ('teacher_email_1', models.EmailField(max_length=254)),
                ('teacher_email_2', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='student_section',
            field=models.CharField(default=10, max_length=500),
            preserve_default=False,
        ),
    ]
