# Generated by Django 2.2.8 on 2019-12-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0002_auto_20191225_0706'),
    ]

    operations = [
        migrations.CreateModel(
            name='super_email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
