# Generated by Django 2.2.7 on 2019-11-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='phy_broken_eq',
            fields=[
                ('bio_eq_id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_id', models.PositiveIntegerField()),
                ('bio_eq_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='phy_eq',
            fields=[
                ('bio_eq_id', models.IntegerField(primary_key=True, serialize=False)),
                ('bio_eq_name', models.CharField(max_length=50)),
                ('bio_eq_amount', models.PositiveIntegerField()),
                ('bio_eq_cost', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='bio_broken_eq',
            name='student',
        ),
        migrations.DeleteModel(
            name='bio_eq',
        ),
        migrations.DeleteModel(
            name='bio_broken_eq',
        ),
    ]
